#!/bin/sh

# ----------------------------------------------------------------
# Initialization
# ----------------------------------------------------------------

set -e

PREVIOUS_WORKING_DIRECTORY="$(pwd)"
REPOSITORY_PATH="$(dirname "$(cd "$(dirname "$0")"; pwd)")"

function on_exit {
	cd "$PREVIOUS_WORKING_DIRECTORY"
}

trap on_exit EXIT
cd "$REPOSITORY_PATH"

# ----------------------------------------------------------------
# Functions
# ----------------------------------------------------------------

function join_by {
	local IFS="$1"
	shift
	echo "$*"
}

function swift_executable {
	local EXECUTABLE_NAME="$1"
	swift build --configuration release --product "$EXECUTABLE_NAME"
	echo "$(swift build --configuration release --product "$EXECUTABLE_NAME" --show-bin-path)/$EXECUTABLE_NAME"
}

# ----------------------------------------------------------------
# .gitignore
# ----------------------------------------------------------------

GITIGNORE_PATH='.gitignore'
STANDARD_GITIGNORE_KEYWORDS_PATH='Settings/standard_gitignore_keywords.txt'
CUSTOM_GITIGNORE_PATH='Settings/custom_gitignore.txt'
STANDARD_GITIGNORE_DOWNLOAD_URL='https://www.gitignore.io/api/'"$(join_by ',' $(<"$STANDARD_GITIGNORE_KEYWORDS_PATH"))"

echo '# ATTENTION: Do not edit this file directly. Refer to **.gitignore** section of `Scripts/configure.sh`.' > "$GITIGNORE_PATH"
curl --silent "$STANDARD_GITIGNORE_DOWNLOAD_URL" >> "$GITIGNORE_PATH"
echo "\n/$GITIGNORE_PATH" >> "$GITIGNORE_PATH"
echo "$(<"$CUSTOM_GITIGNORE_PATH")" >> "$GITIGNORE_PATH"

# ----------------------------------------------------------------
# Miscellaneous
# ----------------------------------------------------------------

# brew install sqlite3
